### ISSUE TITLE
[Discussion] I integrated Figma Linux Font Helper into my project

### ISSUE THREAD

**Issue by atraest** [tryvin/figma-linux-font-helper#7]
Hello @tryvin! I just wanted to drop a quick note to let you know that I'm using **Figma Linux Font Helper** into my project, [Figwrapper](https://github.com/cristianovitorino/figwrapper), a script that fully integrates the Figma design tool (web version)  into a complete app for Linux, and now thanks to your work, with local font support.

Really, thank you.

_Muito obrigado mesmo, e continue o bom trabalho, valeus, um abraço!_

**Comment by tryvin** [comment]
Nice! Be very welcome, hope you enjoyed it, and people can contribute to improve it :)

Pt: Obrigado mesmo! Contribuições como a sua são importantes

**Comment by Brin-o** [comment]
Hello! I am looking to add a folder where fonts are pulled from to inside of Figwrapper using your tool @tryvin. Is this possible? I can't find anything about it in the documentation. Thanks!

**Comment by tryvin** [comment]
Hey @Brin-o , sadly I'm not fully aware of how @estatra did the integration with the wrapper. If the wrapper runs in normal application mode it will query all fonts from your system, so you would install the fonts on your system, and restart the wrapper.

If it's running as a docker container (which I don't think is the case, as it would add docker as a dependency), you would add this folder to the volumes mapping.
