### ISSUE TITLE
Docker mode does not recognizing user fonts

### ISSUE THREAD

**Issue by leinardi** [tryvin/figma-linux-font-helper#8]
If I start the docker mode with just ` docker-compose up` if does not recognize the font installed on the user that is tarting it. To make the fonts available I have to manually specify the default path: `FONT_FOLDER=~/.local/share/fonts docker-compose up`. 
Is this expected?

**Comment by tryvin** [comment]
@leinardi by default it will try to use /usr/share/fonts, if your system fonts are not into this path, you might need to tweek the FONT_FOLDER variable

**Comment by leinardi** [comment]
I see, what about checking by default also the [default user font directory](https://wiki.archlinux.org/index.php/fonts#Manual_installation)? I think it would be a nice QOL improvement.
With the current implementation it can be confusing because, by default, the server will see only system fonts and not user fonts.

**Comment by tryvin** [comment]
@leinardi Well, it's just a matter of mapping another docker volume, I think we can add it as default in the docker-compose file, but it probably would need to be mapped to the /usr/share/fonts inside the container

**Comment by tryvin** [comment]
@leinardi I updated the `docker-compose.yml` file to add a sample on how you would add extra folders
